apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-control-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-control-hub
  template:
    metadata:
      labels:
        app: devops-control-hub
    spec:
      containers:
        - name: web
          image: jimycp1234/devops-control-hub:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
